# https://github.com/ryanking13/twitter-lyric-bot/blob/master/.github/workflows/tweet.yml
name: Post tweet

on:
  schedule:
    - cron: "0 0/1 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm test
      - name: Alarm
        env:
          GITHUB_ACCESS_KEY: ${{ secrets.GITHUB_ACCESS_KEY }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        run: |
          python run.py
